const express=require('express')
const session=require('express-session')
const app=express()

const path=require('path')
const passport=require('passport')
const passport_as=require('./passport_setup')

app.use(session({
    secret:'somesecretstring'
}))
app.use(passport.initialize())
app.use(passport.session())


app.use(express.json())
app.use(express.urlencoded({extended:true}))

app.use('/', express.static(path.join(__dirname, 'public_static')))
app.use('/description', express.static(path.join(__dirname, 'public_static/all_description')))
app.use('/description/Content_Developer_Maths_&_Science_K_10', express.static(path.join(__dirname, 'public_static/description_1')))
app.use('/description/Primary_School_Teacher_in_KP_EDUCATIONAL_ACADEMY', express.static(path.join(__dirname, 'public_static/description_2')))
app.use('/description/Teachers_for_Reputed_Schools_Dharmapuri_Salem', express.static(path.join(__dirname, 'public_static/description_3')))
app.use('/description/Hiring_PGT_Teachers_for_Renowned_CBSE_School_II_Lakhimpur_u.p', express.static(path.join(__dirname, 'public_static/description_4')))
app.use('/description/Hiring_Teachers_Reputed_CBSE_School_II_Greater_Noida', express.static(path.join(__dirname, 'public_static/description_5')))
app.use('/description/Urgent_Requirement_For_School_Teacher_All_Subject_Delhi_NCR', express.static(path.join(__dirname, 'public_static/description_6')))
app.use('/description/Walk_in_Interviews_for_PTI_Teachers_in_Alpine_Convent_School', express.static(path.join(__dirname, 'public_static/description_7')))

app.use('/contact-us', express.static(path.join(__dirname, 'public_static/contactus')))
app.use('/account/login',express.static(path.join(__dirname,'public_static/login')))
app.use('/account/signup',express.static(path.join(__dirname,'public_static/signup')))
app.use('/jobs_in_delhi',express.static(path.join(__dirname,'public_static/jobs_location/jobs_in_delhi')))
app.use('/jobs_in_chandigarh',express.static(path.join(__dirname,'public_static/jobs_location/jobs_in_chandigarh')))
app.use('/jobs_in_chennai',express.static(path.join(__dirname,'public_static/jobs_location/jobs_in_chennai')))
app.use('/jobs_in_jaipur',express.static(path.join(__dirname,'public_static/jobs_location/jobs_in_jaipur')))
app.use('/jobs_in_kolkata',express.static(path.join(__dirname,'public_static/jobs_location/jobs_in_kolkata')))
app.use('/jobs_in_mumbai',express.static(path.join(__dirname,'public_static/jobs_location/jobs_in_mumbai')))
app.use('/jobs_in_pune',express.static(path.join(__dirname,'public_static/jobs_location/jobs_in_pune')))

app.use('/DIET_Jobs',express.static(path.join(__dirname,'public_static/jobs_by_education/DIET_Jobs')))
app.use('/MEd_Jobs',express.static(path.join(__dirname,'public_static/jobs_by_education/MEd_Jobs')))
app.use('/BA_Jobs',express.static(path.join(__dirname,'public_static/jobs_by_education/BA_Jobs')))
app.use('/BBA_Jobs',express.static(path.join(__dirname,'public_static/jobs_by_education/BBA_Jobs')))
app.use('/BEd_Jobs',express.static(path.join(__dirname,'public_static/jobs_by_education/BEd_Jobs')))
app.use('/BTech_Jobs',express.static(path.join(__dirname,'public_static/jobs_by_education/BTech_Jobs')))
app.use('/BSc_Jobs',express.static(path.join(__dirname,'public_static/jobs_by_education/BSc_Jobs')))
app.use('/api', require('./routes').route)
app.use('/details',require('./routes/details').roote)
app.use('/google', require('./routes/google').goo)
app.use('/title',require('./routes/title').title)
app.use('/articles/howtogetajob',express.static(path.join(__dirname,'public_static/job_search_tips')))
app.use('/articles/resume_writing_tips',express.static(path.join(__dirname,'public_static/resume_writing_tips')))
app.use('/termsconditions',express.static(path.join(__dirname,'public_static/termsconditions')))
app.use('/recruiter',express.static(path.join(__dirname,'public_static/new_recruiter_details')))
app.listen(4444,()=>{console.log('listening to port http://localhost:4444')})
